using System.Globalization;
using Tamagotchiたまごっち;

Tamagotchi tamagotchi = new();
tamagotchi.words =new List<string> () {"hi","hello"};
tamagotchi.Hi();
tamagotchi.PrintStats();
tamagotchi.Tick();
tamagotchi.Teach(string word);
tamagotchi.PrintStats();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.ReduceBoredom();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.Feed();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.ReduceBoredom();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.Feed();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.ReduceBoredom();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.Feed();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.ReduceBoredom();
tamagotchi.Tick();
tamagotchi.PrintStats();
tamagotchi.Feed();
tamagotchi.Tick();
tamagotchi.PrintStats();
Console.WriteLine("fij");
Console.ReadLine();